---
title: "Introduction to Programming for PhD students in Education, Harvard University"
subtitle: "Programming, Tools, R, Stata, and More"
details: |
  EDU • Spring 2024<br>HGSE, Harvard University
sidebar: false
toc: false
page-layout: full
format:
  html:
    template-partials:
      - html/home/title-block.html
course-logo: /files/img/logo.png
---

::::: {.home}

Hello, I'm Rony Rodriguez-Ramirez (G1), and this website is my personal project to provide PhD students in Education with tutorials, resources, and tools aimed at enhancing their research and academic skills. This initiative is designed to support your journey through the PhD program with practical and accessible learning materials.

## About This Project

This project is a work in progress, and I am constantly looking to update and improve the content. I welcome any suggestions, feedback, or contributions you might have.

## Tutorials

I've crafted these tutorials to cater to a broad spectrum of needs, from the basics of statistical analysis using R, to more nuanced discussions on quantitative research methodologies. Here are a few highlights:

- To complete

## Additional Resources

- To complete

Thank you for visiting, and I hope you find these resources helpful on your academic path!

:::::

